#ifndef GATING_FXNS
#define GATING_FXNS
  double gpe_ainf(double);
  double gpe_hinf(double);
  double gpe_minf(double);
  double gpe_ninf(double);
  double gpe_rinf(double);
  double gpe_sinf(double);
  double gpe_tauh(double);
  double gpe_taun(double);
  double Hinf(double);
  double stn_ainf(double);
  double stn_binf(double);
  double stn_cinf(double);
  double stn_hinf(double);
  double stn_minf(double);
  double stn_ninf(double);
  double stn_rinf(double);
  double stn_sinf(double);
  double stn_tauc(double);
  double stn_tauh(double);
  double stn_taun(double);
  double stn_taur(double);
  double th_hinf(double);
  double th_minf(double);
  double th_pinf(double);
  double th_rinf(double);
  double ah(double);
  double bh(double);
  double th_tauh(double);
  double th_taur(double);
#endif
