% This script initializes matrices for input-output initialization
InpRCTXtoIDSTR=zeros(n,1);
InpRCTXtoDSTR=zeros(n,1);
InpSTNtoGPE_ampa1=zeros(n,1); %ctrl+f ILIJA
InpSTNtoGPE_ampa2=zeros(n,1); 
InpSTNtoGPI1=zeros(n,1); 
InpSTNtoGPI2=zeros(n,1); 
InpSTNtoGPE_nmda1=zeros(n,1); 
InpSTNtoGPE_nmda2=zeros(n,1); 
InpGPEtoSTN1=zeros(n,1); 
InpGPEtoSTN2=zeros(n,1); 
InpGPEtoGPI1=zeros(n,1);
InpGPEtoGPI2=zeros(n,1);
InpGPEtoGPE=zeros(n,1);
InpGPEtoGPE1=zeros(n,1); 
InpGPEtoGPE2=zeros(n,1); 
InpGPItoTH=zeros(n,1); 
InpSTRtoGPE1=zeros(n,1);
InpSTRtoGPE2=zeros(n,1);
InpSTRtoGPE3=zeros(n,1);
InpSTRtoGPE4=zeros(n,1);
InpSTRtoGPE5=zeros(n,1);
InpSTRtoGPE6=zeros(n,1);
InpSTRtoGPE7=zeros(n,1);
InpSTRtoGPE8=zeros(n,1);
InpSTRtoGPE9=zeros(n,1);
InpSTRtoGPE10=zeros(n,1);
InpSTRtoGPI1=zeros(n,1); 
InpRCTXtoSTR=zeros(n,1); %BOTH OF THEM (id and d)!
InpRCTXtoSTN_ampa1=zeros(n,1);
InpRCTXtoSTN_nmda1=zeros(n,1);
InpRCTXtoSTN_nmda2=zeros(n,1);
InpRCTXtoSTN_ampa2=zeros(n,1);
InpSTRtoGPI2=zeros(n,1);
InpSTRtoGPI3=zeros(n,1);
InpSTRtoGPI4=zeros(n,1);
InpSTRtoGPI5=zeros(n,1);
InpSTRtoGPI6=zeros(n,1);
InpSTRtoGPI7=zeros(n,1);
InpSTRtoGPI8=zeros(n,1);
InpSTRtoGPI9=zeros(n,1);
InpSTRtoGPI10=zeros(n,1);
InpTHtoRCTX=zeros(n,1);
OutICTX=zeros(n,1); 
OutRCTX=zeros(n,1);
InpRCTXtoRCTX=zeros(n,1);
InpICTXtoICTX=zeros(n,1);

pickItoR1 = randsample(n,n);
pickItoR2 = randsample(n,n);
pickItoR3 = randsample(n,n);
pickItoR4 = randsample(n,n);

pickRtoI1 = randsample(n,n);
pickRtoI2 = randsample(n,n);
pickRtoI3 = randsample(n,n);
pickRtoI4 = randsample(n,n);